create table hcq_subject(
	id int(10) auto_increment not null,
	account_id int(10),
	user_name char(18),
	user_portrait varchar(300),
	user_icons varchar(1000),
	subject_title char(50),
	subject_content text(500),
	subject_pictrues varchar(10000),
	publish_date_time datetime,
	publish_from_group_id int(10),
	publish_from_group char(20),
	subject_comment_count int,
	subject_reply_count int,
	subject_laud_count int,
	subject_is_collection tinyint(1),
	primary key (id)
) ENGINE=MyISAM character set utf8

insert into hcq_subject(
	account_id,
	user_name,
	user_portrait,
	user_icons,
	subject_title,
	subject_content,
	subject_pictrues,
	publish_date_time,
	publish_from_group_id,
	publish_from_group,
	subject_comment_count,
	subject_reply_count,
	subject_laud_count,
	subject_is_collection) 
	values(
	1,
	'user one',
	'uploads/users/u140.png',
	'uploads/small-icon.png',
	'话题标题 one',
	'话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文',
	'uploads/contents/u73.jpg,uploads/contents/u75.jpg,uploads/contents/u77.jpg,uploads/contents/u79.jpg',
	'2014-07-10 11:10',
	'1',
	'圈子名称 noe',
	22,
	22,
	22,
	1);

	insert into hcq_subject(
	account_id,
	user_name,
	user_portrait,
	user_icons,
	subject_title,
	subject_content,
	subject_pictrues,
	publish_date_time,
	publish_from_group_id,
	publish_from_group,
	subject_comment_count,
	subject_reply_count,
	subject_laud_count,
	subject_is_collection) 
	values(
	2,
	'user two',
	'uploads/users/u155.png',
	'uploads/small-icon.png',
	'话题标题 two 111',
	'话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文',
	'uploads/contents/u79.jpg,uploads/contents/u81.jpg,uploads/contents/u83.jpg',
	'2014-07-10 11:20',
	'2',
	'圈子名称 two',
	222,
	222,
	222,
	0);

insert into hcq_subject(
	account_id,
	user_name,
	user_portrait,
	user_icons,
	subject_title,
	subject_content,
	subject_pictrues,
	publish_date_time,
	publish_from_group_id,
	publish_from_group,
	subject_comment_count,
	subject_reply_count,
	subject_laud_count,
	subject_is_collection) 
	values(
	2,
	'user two',
	'uploads/users/u155.png',
	'uploads/small-icon.png',
	'话题标题 one',
	'话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文',
	'uploads/contents/u79.jpg,uploads/contents/u81.jpg,uploads/contents/u83.jpg',
	'2014-07-10 11:10',
	'2',
	'圈子名称 two',
	333,
	333,
	333,
	1);


insert into hcq_subject(
	account_id,
	user_name,
	user_portrait,
	user_icons,
	subject_title,
	subject_content,
	subject_pictrues,
	publish_date_time,
	publish_from_group_id,
	publish_from_group,
	subject_comment_count,
	subject_reply_count,
	subject_laud_count,
	subject_is_collection) 
	values(
	3,
	'user three',
	'uploads/users/u533.png',
	'uploads/small-icon.png',
	'话题标题 three',
	'话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文',
	'uploads/contents/u199.jpg,uploads/contents/u277.jpg,uploads/contents/u279.jpg',
	'2014-07-10 11:10',
	'3',
	'圈子名称 three',
	4444,
	3444,
	5555,
	1);


	insert into hcq_subject(
	account_id,
	user_name,
	user_portrait,
	user_icons,
	subject_title,
	subject_content,
	subject_pictrues,
	publish_date_time,
	publish_from_group_id,
	publish_from_group,
	subject_comment_count,
	subject_reply_count,
	subject_laud_count,
	subject_is_collection) 
	values(
	3,
	'user three',
	'uploads/users/u533.png',
	'uploads/small-icon.png',
	'话题标题 three 11111',
	'话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文',
	'uploads/contents/u199.jpg,uploads/contents/u277.jpg,uploads/contents/u279.jpg',
	'2014-07-10 11:40',
	'3',
	'圈子名称 three',
	4444,
	3444,
	5555,
	1);


insert into hcq_subject(
	account_id,
	user_name,
	user_portrait,
	user_icons,
	subject_title,
	subject_content,
	subject_pictrues,
	publish_date_time,
	publish_from_group_id,
	publish_from_group,
	subject_comment_count,
	subject_reply_count,
	subject_laud_count,
	subject_is_collection) 
	values(
	4,
	'user four',
	'uploads/users/u473.png',
	'uploads/small-icon.png',
	'话题标题 four',
	'话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文话题内容正文',
	'uploads/contents/u283.jpg,uploads/contents/u437.jpg,uploads/contents/u495.jpg',
	'2014-07-10 13:20',
	'4',
	'圈子名称 four',
	7777,
	8888,
	9999,
	0);